### ISSUE TITLE
Update Scheming to 2.1.0 to match validation min level

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckan-qld-infrastructure#217]
https://github.com/qld-gov-au/ckan-qld-infrastructure/blob/40584308038cd1a039d809c402b4924120093992/vars/shared-OpenData.var.yml#L58

    CKANExtScheming: &CKANExtScheming
      name: "ckanext-scheming-{{ Environment }}"
      shortname: "ckanext-scheming"
      description: "CKAN Extension for Scheming"
      type: "git"
      url: "https://github.com/ckan/ckanext-scheming.git"
      version: "release-2.1.0"

**Comment by ThrawnCA** [comment]
https://github.com/qld-gov-au/ckan-qld-infrastructure/pull/218 should resolve this.
